### ISSUE TITLE
Can't paste code from the clipboard (windows)

### ISSUE THREAD

**Issue by rsousacode** [HaSa1002/codetranslator#1]
**Version:** 0.1 (Build 2020-08-02 1:38)
Windows 10
Firefox 79.0

**Description of the problem:**
Can't paste code using the online tool

**Steps to reproduce:**
Try copy paste some gdscript code and paste it 
It'll not paste the code

**Code:**
N/A
<details>
<summary>Source Code</summary>

```gdscript

```

</details>
<details>
<summary>Output</summary>

```csharp

```

</details>
<details>
<summary>Expected Output</summary>
N/A

</details>
<details>
<summary>Warnings</summary>
N/A

</details>

**Comment by HaSa1002** [comment]
That is a bug in the HTML Export and Firefox. You can workaround clicking Edit->Paste and then press Ctrl+V

**Comment by HaSa1002** [comment]
See https://github.com/godotengine/godot/issues/12587

**Comment by HaSa1002** [comment]
I hope to include a working paste button eventually, to workaround this bug

**Comment by HaSa1002** [comment]
So an automatic workaround is not possible. This can only be fixed if Firefox one day supports the Clipboard API for more than extensions
